/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2.vista;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import proyecto2.controlador.Controlador;
import proyecto2.model.TrianguloParImpar;
import proyecto2.model.TrianguloPascal;


/**
 *
 * @author Jonathan Camacho
 */
public class VentanaTriangulo extends javax.swing.JFrame  {
    JPanel pane;
    private Controlador elControl ;
    
    public VentanaTriangulo () {
        initComponents();
        
        /*int numero=Integer.parseInt((String)jBoxCantidad.getSelectedItem());
        TrianguloPascal triangulo=new TrianguloPascal(10);
        System.out.println(triangulo.getFilas());
        
        
        GridBagConstraints gbc = new GridBagConstraints();
        //int grid[][]={{1},{1,2,1},{1,2,2,1}};
            for (int i = 0; i < triangulo.getFilas().size(); i++) {
                pane = new JPanel();
                for (int j = 0; j < triangulo.getFilas().get(i).size(); j++) {
                    JButton boton=new JButton(String.valueOf(triangulo.getFilas().get(i).get(j).getNumero()));
                    String color=triangulo.getFilas().get(i).get(j).getColor();
                    if (color==null){
                        boton.setBackground(Color.WHITE);
                    }else{
                        boton.setBackground(Color.getColor(color));
                    };
                    boton.setFont(new Font("Dialog", Font.PLAIN, 12));
                    pane.add(boton);
                }
                gbc.gridx=1;
                gbc.gridy=i;
                jPanelPascal.add(pane, gbc);          
            }
            jPanelPascal.validate();
            //pane.setOpaque(false);*/
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jBoxCantidad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanelPascal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBoxActividad = new javax.swing.JComboBox<>();
        JButtonObtenerInfo = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VentanaTriangulo");
        setBackground(new java.awt.Color(102, 102, 102));

        jBoxCantidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        jBoxCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxCantidadActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad:");

        jPanelPascal.setAlignmentX(250.0F);
        jPanelPascal.setAlignmentY(50.0F);
        jPanelPascal.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Accion a realizar:");

        jBoxActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pares e impares", "Diagonales", "Sumas horizontales", "Simetría", "Sucesión de Fibonacci" }));
        jBoxActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxActividadActionPerformed(evt);
            }
        });

        JButtonObtenerInfo.setText("Obtener información de la acción");
        JButtonObtenerInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonObtenerInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPascal, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBoxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(JButtonObtenerInfo)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBoxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jBoxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JButtonObtenerInfo))))
                .addGap(18, 18, 18)
                .addComponent(jPanelPascal, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBoxCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxCantidadActionPerformed
        jPanelPascal.removeAll();//limbiar el panel para cargar los nuevos datos.
        int numero = Integer.parseInt((String) jBoxCantidad.getSelectedItem());
        TrianguloPascal triangulo = new TrianguloPascal(numero);
        //elControl.crearTriangulo(numero);
        //System.out.println(elControl.crearTriangulo(numero).getFilas());

        GridBagConstraints gbc = new GridBagConstraints();
        for (int i = 0; i < triangulo.getFilas().size(); i++) {
            pane = new JPanel();
            for (int j = 0; j < triangulo.getFilas().get(i).size(); j++) {
                JButton boton = new JButton(String.valueOf(triangulo.getFilas().get(i).get(j).getNumero()));
                String color = triangulo.getFilas().get(i).get(j).getColor();
                if (color == null) {
                    boton.setBackground(Color.WHITE);
                } else {
                    boton.setBackground(Color.getColor(color));
                };
                boton.setFont(new Font("Dialog", Font.PLAIN, 12));
                pane.add(boton);
            }
            gbc.gridx = 1;
            gbc.gridy = i;
            jPanelPascal.add(pane, gbc);
        }
        jPanelPascal.validate();
        jPanelPascal.repaint();//volver a rellenar por si hay cambios
    }//GEN-LAST:event_jBoxCantidadActionPerformed

    private void JButtonObtenerInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonObtenerInfoActionPerformed
        JFrame VentanaInformacion = new JFrame("Información");
        VentanaInformacion.pack();
        VentanaInformacion.setResizable(false);
        VentanaInformacion.setVisible(true);
        VentanaInformacion.setLayout(null);
        VentanaInformacion.setSize(400, 500);
        VentanaInformacion.setLocationRelativeTo(null);
        VentanaInformacion.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);// TODO add your handling code here:
        VentanaInformacion.getContentPane().setBackground(Color.white);
    }//GEN-LAST:event_JButtonObtenerInfoActionPerformed

    private void jBoxActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxActividadActionPerformed
        String eleccion=(String) jBoxCantidad.getSelectedItem();
        switch(eleccion){
            case "Par e impares":
                int numero = Integer.parseInt((String) jBoxCantidad.getSelectedItem());
                TrianguloParImpar trianguloParImpar = new TrianguloParImpar(numero);
                
                
        }
    }//GEN-LAST:event_jBoxActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTriangulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTriangulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonObtenerInfo;
    private javax.swing.JComboBox<String> jBoxActividad;
    private javax.swing.JComboBox<String> jBoxCantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelPascal;
    // End of variables declaration//GEN-END:variables
}
